apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: app
    image: k8s-gr4/rust-app
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    env:
    - name: K8SGR4_LOG
      value: info
    - name: K8SGR4_PORT
      value: "8080"
    - name: MARIADB_HOST
      value: host.docker.internal:3306
    - name: MARIADB_DATABASE
      value: todolist
    - name: MARIADB_USER
      value: some-user
    - name: MARIADB_PASSWORD
      value: some-pwd
    - name: MARIADB_TABLE
      value: main
    args:
    - "--add-host=host.docker.internal:host-gateway"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
  - name: db
    image: mariadb
    ports:
    - containerPort: 3036
    env:
    - name: "MARIADB_USER"
      value: "some-user"
    - name: "MARIADB_PASSWORD"
      value: "some-pwd"
    - name: "MARIADB_ROOT_PASSWORD"
      value: "root-pwd"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
