#!/bin/bash
# compile application in a seperate container with static linking
docker run --rm -it --user "$(id -u)":"$(id -g)" \
    -v "$PWD":/usr/src/myapp \
    -w /usr/src/myapp \
    ekidd/rust-musl-builder \
    cargo build --release
# build the docker image
docker build -t k8s-gr4/app-rust --rm .
