[package]
name = "k8s-gr4"
version = "0.1.0"
edition = "2018"

[dependencies]
dotenv = "0.15"
log = "0.4.16"
env_logger = "0.9"

sqlx = { version = "0.5", features = [ "runtime-actix-native-tls" , "mysql" ] }
actix-web = "4"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
