#!/bin/bash
# exec container from img
docker run --detach \
    -p 8080:8080 \
    --name k8s-gr4-app \
    --env APP_LOG=info \
    --env APP_PORT=8080 \
    --env APP_SECRET=some-secret \
    --env POOL_HOST=172.17.0.2:3306 \
    --env POOL_DATABASE=todolist \
    --env POOL_USER=gr4 \
    --env POOL_PASSWORD=Gruppe4PI19dhge2022 \
    --env POOL_TABLE=main \
    k8s-gr4/app-rust
