#!/bin/bash
id=$(docker container ls -a --filter name=k8s-gr4-app-dev -q)
if [ "$id" != "" ]
then
    docker container stop $id
    docker container rm $id
fi

# exec container from image
docker run -p 8080:8080 \
    --detach \
    --add-host=host.docker.internal:host-gateway \
    --name k8s-gr4-app-dev \
    -e APP_LOG=debug \
    -e APP_SECRET=some-secret \
    -e POOL_HOST=host.docker.internal:3306 \
    -e POOL_DATABASE=todolist \
    -e POOL_USER=gr4 \
    -e POOL_PASSWORD=Gruppe4PI19dhge2022 \
    -e POOL_TABLE=main \
    k8s-gr4/app-rust
