FROM severalnines/mariadb:10.1
ENV MYSQL_ROOT_PASSWORD=root-pwd
ENV MYSQL_ROOT_USER=root
ENV MYSQL_USER=some-user
ENV MYSQL_PASSWORD=some-pwd
ENV MYSQL_DATABASE=todolist
ENV CLUSTER_NAME=mariadb_galera
# WORKDIR /docker-entrypoint-initdb.d
# COPY schema.sql .
